backend/controllers/ManagecategoryController.php
<?php
namespace backend\controllers;
use yii;
use common\models\Category;
use common\models\Mainservice;
use common\models\Measurement;
use common\models\Servicemeasurement;
class ManagecategoryController extends AdminController
{
	public function beforeAction($action) {
		$this->enableCsrfValidation = ($action->id !== "getcurrentCityBylatlan"); // <-- here
		$this->enableCsrfValidation = ($action->id !== "getcategorylist");
		return parent::beforeAction($action);
	}
    public function actionIndex()
    {
    	$response=array();
    	$mainservicelist = Mainservice::getMainservice(1);
    	$measurementlist = Measurement::getMeasurement('',1);
    	if(isset($_REQUEST['category_id']) && $_REQUEST['act']=="edit"){
    		$category_id=$_REQUEST['category_id'];
    		$measurementIds = array();
    		$allmeasurement = Servicemeasurement::getServiceMeasurement($category_id); 
    		foreach ($allmeasurement as $measurements){
    			$measurementIds[] = $measurements['measurement_id'];
    		}
    		$categorydetails=Category::findOne($category_id);
    		$response['measurementIds'] = $measurementIds;
    		$response['categorydetail']=$categorydetails;
    		 
    	}elseif(isset($_REQUEST['category_id']) && $_REQUEST['act']=="delete"){
    		$categorydetails=Category::findOne($_REQUEST['category_id']);
    		if($categorydetails->delete()){
    			$msg="Subservice has been successfully deleted";
    			$status=1;
    			Yii::$app->getSession()->setFlash('status',$status);
    			Yii::$app->getSession()->setFlash('msg',$msg);
    			$this->redirect(Yii::$app->getUrlManager()->getBaseUrl()."/categorylist");
    		}
    	}
    	$response['measurementlist']=$measurementlist;
    	$response['mainservicelist'] = $mainservicelist;
    	return $this->render('index',$response);
    }
	
    /**
     *  Add and Edit Category
     */
    
    public function actionOnpost(){
    	$msg="Oops there is some technical problem";
    	$status=0;
    	$category_id =0;
    	if(isset($_REQUEST['act']) && $_REQUEST['act']=="edit" && isset($_REQUEST['category_id'])){
    		$category_id=$_REQUEST['category_id'];
    		$categoryModel=Category::findOne($category_id);
    		 
    	}else{
    		$categoryModel=new Category();
    	}
    	$categoryModel->mainservice_id=$_REQUEST['mainservice_id'];
    	$categoryModel->category_name=$_REQUEST['category_name'];
    	
    	$categoryModel->category_description=$_REQUEST['category_description'];
    	$categoryModel->category_image=$_REQUEST['category_img_path'];
    	
    	if(isset($_REQUEST['is_active']) && $_REQUEST['is_active']=="on"){
    		$categoryModel->is_active=1;
    	}else{
    		$categoryModel->is_active=0;
    	}
    
    	if(isset($_REQUEST['act']) && $_REQUEST['act']=="edit" && isset($_REQUEST['category_id'])){
    		$categoryModel->updated_on = date('Y-m-d H:i:s');
    		$categoryModel->updated_by = Yii::$app->session['user_id'];
    		if($categoryModel->update()){
    			$status=1;
    			$msg="Subservice has been successfully updated";
    		}else{
    			$status=1;
    			$msg="There is No change to save";
    		}
    	}else{
    		$categoryModel->created_on = date('Y-m-d H:i:s');
    		$categoryModel->created_by = Yii::$app->session['user_id'];;
    		if($categoryModel->save()){ 
    			$category_id=$categoryModel->category_id;
    			$status=1;
    			$msg="Subservice has been successfully added";
    		}
    	}
    	Servicemeasurement::deleteAll('category_id = :category_id',[':category_id' => $category_id]);
    	foreach ($_REQUEST['measurement_id'] as $measurement_id){
    		$mappingModel = new Servicemeasurement();
    		$mappingModel->category_id = $category_id;
    		$mappingModel->measurement_id = $measurement_id;
    		$mappingModel->save();
    		
    	}
    	Yii::$app->getSession()->setFlash('status',$status);
    	Yii::$app->getSession()->setFlash('msg',$msg);
    	$this->redirect(Yii::$app->getUrlManager()->getBaseUrl()."/categorylist");
    }
    
    public function actionGetcategorylist(){
    	$categorylist =array();
    	if(isset($_REQUEST['mainservice_id']) && !empty($_REQUEST['mainservice_id'])){
    		$mainservice_id=$_REQUEST['mainservice_id'];
    		$categorylistdata=Category::getCategory(1,$mainservice_id);
    		$i=0;
    		foreach ($categorylistdata as $category){
    			$categorylist[$i]['category_id']=$category['category_id'];
    			$categorylist[$i]['category_name']=$category['category_name'];
    			$i++;
    		}
    	}
    	echo  json_encode($categorylist) ;
    }
    
    
    
    
    
    /**
     *  This function responsible to upload a file and return file path
     */
    public function actionUploadimage()
    {
    	$max_width = 100 ;
    	$max_file=10;
    	$detail_max_width = 100;
    	//$detail_max_file = 100;
    	$scale =1 ;
    	$scaleDetail =1 ;
    	error_reporting(E_ERROR ) ;
    	$logoDir = 'uploads/image' ;
    	$thumbDir ='uploads/thumb' ;
    	$detailDir = 'uploads/appdetail' ;
    	if (isset($_FILES['document'])) {
    		//Get the file information
    		$userfile_name = $_FILES['document']['name'];
    		$userfile_tmp =  $_FILES['document']['tmp_name'];
    		$userfile_size = $_FILES['document']['size'];
    		$userfile_type = $_FILES['document']['type'];
    		$filename = basename($_FILES['document']['name']);
    		$ext = strtolower(substr($filename, strrpos($filename, '.') + 1));
    
    		$allowedExt = array('jpg','jpeg','png','gif');
    
    		$docment = array();
    		$docment['id'] = date("Y-m-d").uniqid();
    		$docment['ext'] = $ext ;
    		 
    		//Only process if the file is a JPG, PNG or GIF and below the allowed limit
    		if((!empty($_FILES["document"])) && ($_FILES['document']['error'] == 0)) {
    
    			if(in_array($ext, $allowedExt)){
    				$error = "";
    			}else{
    				$error = "Only <strong>jpg,jpeg,png,gif</strong> file accepted for upload<br />";
    			}
    			if ($userfile_size > ($max_file*1048576)) {
    				$error.= "Images must be under ".$max_file."MB in size";
    			}
    			$docment['status']=0;
    			if(strlen($error)!=0){
    				$docment['error']=$error;
    			}
    
    		}else{
    			$error= "Select an file for upload";
    		}
    		 
    		if (strlen($error)==0){
    
    			if (isset($_FILES['document']['name'])){
    				//this file could now has an unknown file extension (we hope it's one of the ones set above!)
    
    				$newName = $docment['id'] . '.' . $ext;
    				$tempnewName = 'temp'.$docment['id'] . '.' . $ext;
    				$logo_location = $logoDir . DIRECTORY_SEPARATOR . $newName;
    				//$detailDir_location = $detailDir. DIRECTORY_SEPARATOR . $newName;
    				$thumb_location = $thumbDir . DIRECTORY_SEPARATOR . $newName;
    				move_uploaded_file($userfile_tmp, $logo_location);
    				copy($logo_location, $thumb_location);
    				//copy($logo_location, $detailDir_location);
    				
    				//$detailWidth = $this->getWidth($detailDir_location);
    				//$detailHeight = $this->getHeight($detailDir_location);
    				
    				$width = $this->getWidth($thumb_location);
    				$height = $this->getHeight($thumb_location);
    				
    				/*if ($detailWidth > $max_width){
    					$scale = $max_width/$detailWidth;
    					$uploaded = $this->resizeImage($detailDir_location,$detailWidth,$detailHeight,$scaleDetail);
    				
    				}else{
    					$scale = 1;
    					$uploaded = $this->resizeImage($detailDir_location,$detailWidth,$detailHeight,$scaleDetail);
    				}*/
    				if ($width > $max_width){
    					$scale = $max_width/$width;
    					$uploaded = $this->resizeImage($thumb_location,$width,$height,$scale);
    						
    				}else{
    					$scale = 1;
    					$uploaded = $this->resizeImage($thumb_location,$width,$height,$scale);
    				}
    				$docment['status']=1;
    				$docment['image'] = $logo_location;
    			}
    
    		}
    		echo  json_encode($docment) ;
    		exit();
    	}
    
    
    }
    private function resizeImage($image, $width, $height, $scale) {
    	list ( $imagewidth, $imageheight, $imageType ) = getimagesize ( $image );
    	$imageType = image_type_to_mime_type ( $imageType );
    	$newImageWidth = ceil ( $width * $scale );
    	$newImageHeight = ceil ( $height * $scale );
    	$newImage = imagecreatetruecolor ( $newImageWidth, $newImageHeight );
    	switch ($imageType) {
    		case "image/gif" :
    			$source = imagecreatefromgif ( $image );
    			break;
    		case "image/pjpeg" :
    		case "image/jpeg" :
    		case "image/jpg" :
    			$source = imagecreatefromjpeg ( $image );
    			break;
    		case "image/png" :
    		case "image/x-png" :
    			$source = imagecreatefrompng ( $image );
    			break;
    	}
    	imagecopyresampled ( $newImage, $source, 0, 0, 0, 0, $newImageWidth, $newImageHeight, $width, $height );
    
    	switch ($imageType) {
    		case "image/gif" :
    			imagegif ( $newImage, $image );
    			break;
    		case "image/pjpeg" :
    		case "image/jpeg" :
    		case "image/jpg" :
    			imagejpeg ( $newImage, $image, 90 );
    			break;
    		case "image/png" :
    		case "image/x-png" :
    			imagepng ( $newImage, $image );
    			break;
    	}
    
    	chmod ( $image, 0777 );
    	return $image;
    }
    function getWidth($image) {
    	$size = getimagesize ( $image );
    	$width = $size [0];
    	return $width;
    }
    private function getHeight($image) {
    	$size = getimagesize ( $image );
    	$height = $size [1];
    	return $height;
    }
    private function saveThumb($pathname, $savePathName) {
    	$img = PhpThumbFactory::create ( $pathname );
    	$img->adaptiveResize ( 180, 180 );
    	$img->save ( $savePathName );
    }
    
    
}

backend/views/managecategory/index.php
<script
	src="<?php echo Yii::$app->getUrlManager()->getBaseUrl() ;?>/js/jquery.form.js"> </script>
<script
	src="<?php echo Yii::$app->getUrlManager()->getBaseUrl() ;?>/js/validation/category.js"> </script>
<div class="row">
	<div class="col-md-12">
			<?php if(Yii::$app->session->getFlash('msg')) { ?>
					<div class="<?php if(Yii::$app->session->getFlash('status')==0){?>alert alert-danger<?php }else{?> alert alert-success <?php }?>">
					<p><?php  echo Yii::$app->session->getFlash('msg'); ?></p>
					</div>
			<?php }?>
		<div class="col-md-12">
			<h2>
			<?php if(isset($_REQUEST['category_id']) && $_REQUEST['category_id']){?>
			Edit Subservice
			<?php }else{?>
			Add Subservice
			<?php }?>
			</h2>
		</div>
		<div class="panel panel-primary" data-collapsed="0">


			<div class="panel-body">

				<form role="form" action="managecategory/onpost" method="post" id="category_form"
					class="form-horizontal form-groups-bordered">
					
					<div class="form-group">
							<label class="col-sm-3 control-label">Main service <span class="valError">*</span></label>
								<div class="col-sm-5">
									<select class="form-control" name="mainservice_id" id="mainserviceId" >
										<option value>Select mainservice</option>
										<?php foreach ($mainservicelist as $mainservice){?>
										<option value="<?php echo $mainservice['mainservice_id'];?>" <?php if(isset($categorydetail->mainservice_id) && $categorydetail->mainservice_id==$mainservice['mainservice_id']){?> selected <?php }?>>
										<?php echo $mainservice['mainservice_name'];?></option>
										<?php }?>					
									</select>
								</div>
								<div class="valError">
									<span class="val_mainserviceId"></span>
								</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">Subservice Name <span class="valError">*</span></label>
						<div class="col-sm-5">
							<input type="text" class="form-control" name="category_name" 
								id="categoryname" placeholder="Category Name" 
								value="<?php if(isset($categorydetail->category_name) && $categorydetail->category_name){ echo $categorydetail->category_name;}?>" Required>
						</div>
						<div class="valError">
							<span class="val_categoryname"></span>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label">Subservice Description </label>
						<div class="col-sm-5">
							<input type="text" class="form-control" name="category_description"
								id="categorydescription" placeholder="Subservice Description" 
								value="<?php if(isset($categorydetail->category_description) && $categorydetail->category_description){ echo $categorydetail->category_description;}?>" >
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">Subservice Image <span class="valError">*</span></label>
						<div class="col-sm-3">
							<div class="fileinput fileinput-new" data-provides="fileinput">
								<input type="hidden" id="doc" name="category_img_path" value="<?php if(isset($categorydetail->category_image)){echo $categorydetail->category_image;}?>">
								<div class="input-group">
									<div class="form-control uneditable-input" data-trigger="fileinput">
										<i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
									</div>
									<span class="input-group-addon btn btn-default btn-file"> <span class="fileinput-new">Select File</span> <span class="fileinput-exists">Change</span> <input type="file" name="document" id="documentId">

									</span> <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>

								</div>
								<div style="margin-top: 10px; display:none;" id="loader">
									<img src="<?php echo Yii::$app->getUrlManager()->getBaseUrl() ;?>/images/process.gif" />
								</div>											
							</div>
									
							<div class="col-sm-12 nopadding" id="errormsg">
							<?php if(isset($categorydetail->category_image)){?>
								<img src='<?php echo str_replace("/admin","", Yii::$app->getUrlManager()->getBaseUrl());?>/backend/web/<?php echo $categorydetail->category_image;?>' height="100" width="100">
							<?php }?>
							</div>
					  </div>
					  <div class="valError">
							<span class="val_doc"></span>
						</div>
					</div>
					<div class="form-group">
							<label class="col-sm-3 control-label">Measurement Type <span class="valError">*</span></label>
								<div class="col-sm-5">
									<select class="form-control" name="measurement_id[]" id="measurementId"  multiple required>
										<option value>Select Measurement</option>
										<?php foreach ($measurementlist as $measurement){?>
										<option value="<?php echo $measurement['measurement_id'];?>" <?php if(isset($measurementIds) && !empty($measurementIds) && in_array($measurement['measurement_id'], $measurementIds)){?> selected <?php }?>>
										<?php echo $measurement['measurement_name']." ( ".$measurement['measurement_sort_name']." ) ";?></option>
										<?php }?>					
									</select>
								</div>
								<div class="valError">
									<span class="val_measurementId"></span>
								</div>
								
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label">Is Active</label>

						<div class="col-sm-5">
							<div class="checkbox checkbox-replace color-green">
								<input type="checkbox" name="is_active" id="chk-23"
								<?php if(isset($categorydetail->is_active) && $categorydetail->is_active==0){ }else{?>
									checked <?php }?>/>

							</div>

						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-5">
							<button type="submit" class="btn btn-default" id="save">
							<?php if(isset($categorydetail->category_id) && $categorydetail->category_id){ ?>
							Update
							<?php }else{?>
							Save
							<?php }?>
							</button>
							<input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
							<button type="button" class="btn btn-default" id="cancel">Close</button>
									<?php if(isset($categorydetail->category_id) && $categorydetail->category_id){ ?> 
										<input type="hidden"
											value="<?php echo $categorydetail->category_id; ?>" name="category_id" /> <input
											type="hidden" value="edit" name="act" />
									 <?php }else{?>
									 <input type="hidden" value="add" name="act" />
									 <?php }?>
								</div>
					</div>
				</form>

			</div>

		</div>

	</div>
</div>

<script type="text/javascript">
$("#cancel" ).click(function() {
	window.history.back();
});

$(function(){
	$("#documentId").change(function() { 
		$("#loader").show();
		$("#isdocument").hide();
		 $("#errormsg").hide();
				uploadfile();
	});
});
function uploadfile()
{ 
	$("#image_priview").show();
	$("#save").attr("disabled","disabled")  ;
	$("#category_form")
	.ajaxSubmit({ 
					url : 'managecategory/uploadimage',
					type : 'post',
					success : function(response) {
						 var obj =  jQuery.parseJSON(response) ;
						 $("#loader").hide();
						 if(obj.status==1){
							 if(typeof obj.image!='undefined'){
								 $("#doc").val(obj.image) ;
								 $("#errormsg").show();
								 $("#errormsg").empty();
								// var success="<span style='color: green; '>File uploded successfully, filename :- "+ obj.id +"</span>";
								var success="<img src='<?php echo str_replace("/admin","", Yii::$app->getUrlManager()->getBaseUrl());?>/backend/web/"+ obj.image+"' height='100' width='100'/>";
								 $("#errormsg").append(success);
							 }
						 }else{
							 $("#errormsg").show();
							$("#errormsg").empty();
							var error="<span style='color: red; '>"+ obj.error +"</span>";
							$("#errormsg").append(error);
						 }
						 $("#save").removeAttr("disabled") ;
						
									
					}
				});
}

</script>